# frozen_string_literal: true
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: gol_development
  username: postgres
  password: pgsql
  password: pgsql
  host: localhost
  port: 5432

test:
  <<: *default
  database: gol_test
  username: postgres
  password: pgsql
  host: localhost
  port: 5432

production:
  <<: *default
  database: gol_production
  username: gol
  password: <%= ENV["GOL_DATABASE_PASSWORD"] %>
